apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodeapis-v2
  name: nodeapis-v2-svc
  namespace: ecol
spec:
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodeapis-v2
  sessionAffinity: None
  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodeapis-v2
  name: nodeapis-v2
  namespace: ecol
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nodeapis-v2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nodeapis-v2
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: ecol-config
        - secretRef:
            name: ecol-secrets
        image: docker.io/migutak/oraclenode-apis-v2-lb4-v3:3.1
        imagePullPolicy: IfNotPresent
        name: nodeapis-v2
        ports:
        - containerPort: 6001
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: reg-cred-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
